version: 2.1

#-------------------------------------------Orbs--------------------------------------
orbs:
  flutter-orb: circleci/flutter@1.1.0

#-------------------------------------------Executors--------------------------------------
executors:
  android:
    docker:
      - image: cimg/android:2023.07

#-------------------------------------------Commands--------------------------------------
commands:
  # Install git secret
  install_git_secret:
    description: Install git secret cli
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y git-secret

  # Import gpg key from env var
  import_gpg_key:
    description: Import gpg key from env var
    steps:
      - run: echo -e "$GITHUB_SECRET_KEY"| tr ',' '\n'> ./private_key.gpg
      - run: gpg --batch --yes --pinentry-mode loopback --import private_key.gpg

  # Reveal the secrets files
  reveal_secrets:
    description: Reveal the secrets
    steps:
      - run: git secret reveal -p "$GITHUB_SECRET_PASSPHRASE"

  # Build the APK file
  build_apk:
    description: Build APK
    steps:
      - run:
          command: flutter build apk
          working_directory: android

  # Install Bundler
  install_bundler:
    description: Install bundler
    steps:
      - run:
          command: sudo bundle install
          working_directory: android

  # Distribute Firebase
  distribute_firebase:
    description: Distribute APK to Firebase
    steps:
      - run:
          command: bundle exec fastlane distribute
          working_directory: android

#-------------------------------------------Jobs--------------------------------------
jobs:
  # ------------ Android ------------
  build-firebase-android:
    executor: android
    steps:
      - checkout
      - install_git_secret
      - import_gpg_key
      - reveal_secrets
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - build_apk
      - install_bundler
      - distribute_firebase

#-------------------------------------------Workflows--------------------------------------
workflows:
  build-app:
    jobs:
      - build-firebase-android:
          filters:
            branches:
              only:
                - develop
#-------------------------------------------End--------------------------------------

