version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  distribute-firebase:

  executor:
    name: android/android-machine

    steps:
      - checkout
      - run:
          command: ./gradlew build
          working_directory: android
      - run:
          name: Install fastlane
          command: bundle install
          working_directory: android
      - run:
          name: Execute fastlane
          command: bundle exec fastlane distribute
          working_directory: android

workflows:
  distribute-firebase: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - distribute-firebase
          filters:
            branches:
              only:
                - develop
