version: 2.1

#-------------------------------------------Orbs--------------------------------------
orbs:
  flutter-orb: circleci/flutter@1.1.0

#-------------------------------------------Executors--------------------------------------
executors:
  macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2

#-------------------------------------------Commands--------------------------------------
commands:
  # Install git secret
  install_git_secret:
    description: Install git secret cli
    steps:
      - run: brew install git-secret

  # Import gpg key from env var
  import_gpg_key:
    description: Import gpg key from env var
    steps:
      - run: echo -e "$GITHUB_SECRET_KEY"| tr ',' '\n'> ./private_key.gpg
      - run: gpg --batch --yes --pinentry-mode loopback --import private_key.gpg

  # Reveal the secrets files
  reveal_secrets:
    description: Reveal the secrets
    steps:
      - run: git secret reveal -p "$GITHUB_SECRET_PASSPHRASE"

  # Install Bundler
  install_bundler:
    description: Install bundler & Pod install
    steps:
      - run:
          command: sudo bundle install && pod install
          working_directory: ios

  # Distribute Firebase
  upload_to_testflight:
    description: Upload to Testflight
    steps:
      - run:
          command: bundle exec fastlane beta
          working_directory: ios

#-------------------------------------------Jobs--------------------------------------
jobs:
  build-ios:
    executor: macos
    steps:
      - checkout
      - install_git_secret
      - import_gpg_key
      - reveal_secrets
      - add_ssh_keys:
          fingerprints:
            - "7d:12:83:07:5a:b2:2f:f3:1e:30:16:c9:57:df:a0:ed"
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - install_bundler
      - upload_to_testflight

#-------------------------------------------Workflows--------------------------------------
workflows:
  build-app:
    jobs:
      - build-ios:
          filters:
            branches:
              only:
                - ios
#-------------------------------------------End--------------------------------------

