# version: 2.1

# orbs:
#   flutter-orb: circleci/flutter@1.1.0
#   git-secret: lyvly/git-secret@0.1.0

# executors:
#   android:
#     docker:
#       - image: cimg/android:2022.06

# jobs:
#   # ------------ Android ------------
#   build-firebase-android:
#     executor: android
#     steps:
#       - checkout
#       - flutter-orb/install_sdk_and_pub:
#           flutter_version: 3.7.5
#       - run:
#           command: flutter build apk
#           working_directory: android
#       - run:
#           command: bundle install
#           working_directory: android
#       - run:
#           command: bundle exec fastlane distribute
#           working_directory: android

# workflows:
#   build-app:
#     jobs:
#       - build-firebase-android:
#           filters:
#             branches:
#               only:
#                 - develop

# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing

version: 2.1
description: Use git-secret

commands:
  install_git_secret:
    description: Install git secret cli
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y git-secret

  import_gpg_key:
    description: Import gpg key from env var
    parameters:
      variable_name:
        type: env_var_name
        default: "manhcoder96" # TODO: pass through job
        description: environment variable containing gpg key
    steps:
      - run: echo -e "$<< parameters.variable_name >>" | gpg --import public_keys/*

  reveal_secrets:
    description: Reveal the secrets
    steps:
      - run: git secret reveal -p "manhcoder96"
      - run: echo -e "manhcoder96"
executors:
  default:
    description: Job config
    docker:
      - image: circleci/python:3.8

jobs:
  install_and_decrypt:
    description: Install and set up git secret, then reveal the secrets
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - install_git_secret
      - import_gpg_key
      - reveal_secrets
      - persist_to_workspace:
          root: ./
          paths:
            - ./
workflows:
  build:
    jobs:
      - install_and_decrypt:
          filters:
            branches:
              only:
                - develop
