version: 2.1

orbs:
  # flutter-orb: circleci/flutter@1.1.0
  git-secret: lyvly/git-secret@1

executors:
  git_secret:
    description: Job config
    docker:
      - image: circleci/node:10.16.3
  # android:
  #   docker:
  #     - image: cimg/android:2022.06

commands:
  install_git_secret:
    description: Install git secret cli
    steps:
      - run: sudo apt-get update && sudo apt-get install apt-transport-https
      - run: echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
      - run: wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install git-secret

  import_gpg_key:
    description: Import gpg key from env var
    parameters:
      variable_name:
        type: env_var_name
        default: manhcoder96 # TODO: pass through job
        description: environment variable containing gpg key
    steps:
      - run: echo -e "$<< parameters.variable_name >>" | gpg --import

  reveal_secrets:
    description: Reveal the secrets
    steps:
      - run: git secret reveal -f

jobs:
  # ------------ REVEAL GIT SECRET ------------
  install_and_decrypt:
    description: Install and set up git secret, then reveal the secrets
    executor: git_secret
    steps:
      - install_git_secret
      - import_gpg_key
      - reveal_secrets

  # # ------------ Android ------------
  # build-firebase-android:
  #   executor: android
  #   steps:
  #     - checkout
  #     - flutter-orb/install_sdk_and_pub:
  #         flutter_version: 3.7.5
  #     - run:
  #         command: flutter build apk
  #         working_directory: android
  #     - run:
  #         command: bundle install
  #         working_directory: android
  #     - run:
  #         command: bundle exec fastlane distribute
  #         working_directory: android

workflows:
  build:
    jobs:
      - git-secret/install_and_decrypt:
  # build-app:
  #   jobs:
  #     - flutter-orb/build-firebase-android:
  #         filters:
  #           branches:
  #             only:
  #               - develop
