version: 2.1

orbs:
  flutter-orb: circleci/flutter@1.1.0
  git-secret: lyvly/git-secret@0.1.0

executors:
  git_secret:
    description: Job config
    docker:
      - image: circleci/node:10.16.3

jobs:
  # ------------ Android ------------
  build-firebase-android:
    executor: android
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - run:
          command: flutter build apk
          working_directory: android
      - run:
          command: bundle install
          working_directory: android
      - run:
          command: bundle exec fastlane distribute
          working_directory: android

workflows:
  build-app:
    jobs:
      - git-secret/install_and_decrypt:
          working_directory: public_keys
          variable_name: manhcoder96
      - build-firebase-android:
          filters:
            branches:
              only:
                - develop
