# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

platform :android do
  desc "Firebase distribution"
  lane :distribute do
      release = firebase_app_distribution(
          app: "1:251412403295:android:04d04f7285a96277afb7ea",
          service_credentials_file: "./app/deployment-75bd0-c9cded138464.json",
          apk_path: "../build/app/outputs/apk/release/app-release.apk",
          groups_file: "../release/groups.txt",
          release_notes_file: "../release/notes.txt"
      )
  end
end
